version: '3.1'

services:

  book_store:
    image: postgres:11-alpine
    restart: "no"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: book_store
    ports:
      - 5432:5432